//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "LogoutPage.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string LogoutPage::genText(const DrTemplateData& LogoutPage_view_data)
{
	drogon::OStringStream LogoutPage_tmp_stream;
	std::string layoutName{""};
	LogoutPage_tmp_stream << "<!DOCTYPE html>\n";
	LogoutPage_tmp_stream << "<html>\n";
	LogoutPage_tmp_stream << "<head>\n";
	LogoutPage_tmp_stream << "    <meta charset=\"UTF-8\">\n";
	LogoutPage_tmp_stream << "    <title>session example</title>\n";
	LogoutPage_tmp_stream << "</head>\n";
	LogoutPage_tmp_stream << "	<body>\n";
	LogoutPage_tmp_stream << "	<form action=\"/logout\" method=\"post\">\n";
	LogoutPage_tmp_stream << "		<div class=\"container\">\n";
	LogoutPage_tmp_stream << "			<button type=\"submit\">Logout</button>\n";
	LogoutPage_tmp_stream << "		</div>\n";
	LogoutPage_tmp_stream << "	</form> \n";
LogoutPage_tmp_stream<<"\n";
	LogoutPage_tmp_stream << "	<p>You can logout now</p>\n";
	LogoutPage_tmp_stream << "</body>\n";
	LogoutPage_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(LogoutPage_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = LogoutPage_view_data;
auto str = std::move(LogoutPage_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
